export { default as IntroductionTab } from "./General";
export { default as NDATab } from "./NDALock";
export { default as ProfileTab } from "./Profile";
export { default as RequirementsTab } from "./Requirements";
export { default as DashboardTab } from "./Dashboard";
export { default as PartnersTab } from "./Partners";
export { default as ScopeTab } from "./Scope";
export { default as ScopeDataTab } from "./ScopeData";
export { default as AnalyticsTab } from "./Analytics";
