version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    target-branch: "develop"
    labels:
      - "npm"
      - "dependencies"
    ignore:
      - dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/private/translations"
    schedule: "monthly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/private/semantic"
    schedule: "monthly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/private/semantic"
    schedule: "monthly"
    ignore:
      - dependency-name: "*"
