// import "./010-features.js";
// import "./011-price-list-template-structure";
// import "./012-price-list-carrierName";
// import "./013-priceList-conversions";
// import "./014-address-accounts-structure";
// import "./015-all-accounts-single-collection";
// import "./016-all-partnerShips-to-accounts-collection";
import "./017-add-priceList-template-spot";
import "./018-set-delete-flag-to-false priceList";
import "./019-set-delete-flag-to-false shipments";
import "./020-set-delete-flag-to-false invoices";
import "./021-set-delete-flag-to-false invoiceItems";
import "./022-set-delete-flag-to-false allAccounts";
import "./023-set-delete-flag-to-false tender";
import "./024-set-delete-flag-to-false tenderDetails";
import "./025-denormalize-scope-in-tender";
import "./026-set-delete-flag-to-true priceList";
import "./027-add-sequence-number-to-stages";
import "./028-Meteor-Roles-v3";
import "./029-locationsDB-replaceIndex";
import "./030-locations-reindex-linkedCollections";
import "./031-roles-ensureRolesAreSet";
import "./032-accounts-userIds-in-account-document";
import "./033-costs-isDummy-flag";
import "./034-accounts-custom-data-in-array";
import "./035-roles-add mass priceRequest role";
import "./036-price-request-add-title";
import "./037-roles-add mass priceRequest role";
import "./038-priceRequest notes to slate";
import "./039-roles-add core shipment";
import "./040-shipment project access rules";
import "./041-update-accesskey-shipment";
import "./042-recalculate-open-pricerequests.js";
import "./043-base roles - split out planner";
import "./044-address-notes-to-slate";
import "./045-remove old analysis";
import "./046-numidia-script-as-account-setting.js";
import "./047-accounts-add-roles";
import "./048-denormalize-shipment-dates";
import "./049-set-default-user-notification-prefs";
import "./050-fix-address-zip-zipCode.js";
import "./051-reset-inbound-outbound-project-link";
import "./052-priceRequest-chargeLines--schema-change";
import "./053-tender-bidder-responses-split-out";
import "./054-denormalize-shipment-dates scheduled";
import "./055-settings-data-in-db";
import "./056-denormalize-shipment-dates";
import "./057-add-picking-role";
import "./058-accountId-in-user-doc";
import "./059-parcel-api-costs-reset";
import "./060-remove-duplicate-partners";
