// source: https://cloford.com/resources/codes/index.htm
// ["Continent", "Region", "Country", "Capital", "ISO (2)"],
export const REGION_MAP = [
  ["Asia", "South Asia", "Afghanistan", "Kabul", "AF"],
  ["Europe", "South East Europe", "Albania", "Tirana", "AL"],
  ["Africa", "Northern Africa", "Algeria", "Algiers", "DZ"],
  ["Oceania", "Pacific", "American Samoa", "Pago Pago", "AS"],
  ["Europe", "South West Europe", "Andorra", "Andorra la Vella", "AD"],
  ["Africa", "Southern Africa", "Angola", "Luanda", "AO"],
  ["Americas", "West Indies", "Anguilla", "The Valley", "AI"],
  ["Americas", "West Indies", "Antigua and Barbuda", "Saint John's", "AG"],
  ["Americas", "South America", "Argentina", "Buenos Aires", "AR"],
  ["Asia", "South West Asia", "Armenia", "Yerevan", "AM"],
  ["Americas", "West Indies", "Aruba", "Oranjestad", "AW"],
  ["Oceania", "Pacific", "Australia", "Canberra", "AU"],
  ["Europe", "Central Europe", "Austria", "Vienna", "AT"],
  ["Asia", "South West Asia", "Azerbaijan", "Baku (Baki)", "AZ"],
  ["Americas", "West Indies", "Bahamas, The", "Nassau", "BS"],
  ["Asia", "South West Asia", "Bahrain", "Manama", "BH"],
  ["Asia", "South Asia", "Bangladesh", "Dhaka", "BD"],
  ["Americas", "West Indies", "Barbados", "Bridgetown", "BB"],
  ["Europe", "Eastern Europe", "Belarus", "Minsk", "BY"],
  ["Europe", "Western Europe", "Belgium", "Brussels", "BE"],
  ["Americas", "Central America", "Belize", "Belmopan", "BZ"],
  ["Africa", "Western Africa", "Benin", "Porto-Novo ³", "BJ"],
  ["Americas", "West Indies", "Bermuda", "Hamilton", "BM"],
  ["Asia", "South Asia", "Bhutan", "Thimphu", "BT"],
  ["Americas", "South America", "Bolivia", "La Paz / Sucre", "BO"],
  ["Europe", "South East Europe", "Bosnia and Herzegovina", "Sarajevo", "BA"],
  ["Africa", "Southern Africa", "Botswana", "Gaborone", "BW"],
  ["Americas", "South America", "Brazil", "Brasilia", "BR"],
  ["Americas", "West Indies", "British Virgin Islands", "Road Town", "VG"],
  ["Asia", "South East Asia", "Brunei", "Bandar Seri Begawan", "BN"],
  ["Europe", "South East Europe", "Bulgaria", "Sofia", "BG"],
  ["Africa", "Western Africa", "Burkina Faso", "Ouagadougou", "BF"],
  ["Africa", "Central Africa", "Burundi", "Bujumbura", "BI"],
  ["Asia", "South East Asia", "Cambodia", "Phnom Penh", "KH"],
  ["Africa", "Western Africa", "Cameroon", "Yaounde", "CM"],
  ["Americas", "North America", "Canada", "Ottawa", "CA"],
  ["Africa", "Western Africa", "Cape Verde", "Praia", "CV"],
  ["Americas", "West Indies", "Cayman Islands", "George Town", "KY"],
  ["Africa", "Central Africa", "Central African Republic", "Bangui", "CF"],
  ["Africa", "Central Africa", "Chad", "N'Djamena", "TD"],
  ["Americas", "South America", "Chile", "Santiago", "CL"],
  ["Asia", "East Asia", "China", "Beijing", "CN"],
  ["Asia", "South East Asia", "Christmas Island", "The Settlement", "CX"],
  ["Asia", "South East Asia", "Cocos (Keeling) Islands", "West Island", "CC"],
  ["Americas", "South America", "Colombia", "Bogota", "CO"],
  ["Africa", "Indian Ocean", "Comoros", "Moroni", "KM"],
  ["Africa", "Central Africa", "Congo, Republic of the", "Brazzaville", "CG"],
  ["Oceania", "Pacific", "Cook Islands", "Avarua", "CK"],
  ["Americas", "Central America", "Costa Rica", "San Jose", "CR"],
  ["Africa", "Western Africa", "Cote d'Ivoire", "Yamoussoukro", "CI"],
  ["Europe", "South East Europe", "Croatia", "Zagreb", "HR"],
  ["Americas", "West Indies", "Cuba", "Havana", "CU"],
  ["Asia", "South West Asia", "Cyprus", "Nicosia", "CY"],
  ["Europe", "Central Europe", "Czech Republic", "Prague", "CZ"],
  ["Europe", "Northern Europe", "Denmark", "Copenhagen", "DK"],
  ["Africa", "Eastern Africa", "Djibouti", "Djibouti", "DJ"],
  ["Americas", "West Indies", "Dominica", "Roseau", "DM"],
  ["Americas", "West Indies", "Dominican Republic", "Santo Domingo", "DO"],
  ["Americas", "South America", "Ecuador", "Quito", "EC"],
  ["Africa", "Northern Africa", "Egypt", "Cairo", "EG"],
  ["Americas", "Central America", "El Salvador", "San Salvador", "SV"],
  ["Africa", "Western Africa", "Equatorial Guinea", "Malabo", "GQ"],
  ["Africa", "Eastern Africa", "Eritrea", "Asmara", "ER"],
  ["Europe", "Eastern Europe", "Estonia", "Tallinn", "EE"],
  ["Africa", "Eastern Africa", "Ethiopia", "Addis Ababa", "ET"],
  [
    "Americas",
    "South America",
    "Falkland Islands (Islas Malvinas)",
    "Stanley",
    "FK"
  ],
  ["Europe", "Northern Europe", "Faroe Islands", "Torshavn", "FO"],
  ["Oceania", "Pacific", "Fiji", "Suva", "FJ"],
  ["Europe", "Northern Europe", "Finland", "Helsinki", "FI"],
  ["Europe", "Western Europe", "France", "Paris", "FR"],
  ["Americas", "South America", "French Guiana", "Cayenne", "GF"],
  ["Oceania", "Pacific", "French Polynesia", "Papeete", "PF"],
  ["Africa", "Western Africa", "Gabon", "Libreville", "GA"],
  ["Africa", "Western Africa", "Gambia, The", "Banjul", "GM"],
  ["Asia", "South West Asia", "Georgia", "T'bilisi", "GE"],
  ["Europe", "Western Europe", "Germany", "Berlin", "DE"],
  ["Africa", "Western Africa", "Ghana", "Accra", "GH"],
  ["Europe", "South West Europe", "Gibraltar", "Gibraltar", "GI"],
  ["Europe", "South East Europe", "Greece", "Athens", "GR"],
  ["Americas", "North America", "Greenland", "Nuuk (Godthab)", "GL"],
  ["Americas", "West Indies", "Grenada", "Saint George's", "GD"],
  ["Americas", "West Indies", "Guadeloupe", "Basse-Terre", "GP"],
  ["Oceania", "Pacific", "Guam", "Hagatna (Agana)", "GU"],
  ["Americas", "Central America", "Guatemala", "Guatemala", "GT"],
  ["Africa", "Western Africa", "Guinea", "Conakry", "GN"],
  ["Africa", "Western Africa", "Guinea-Bissau", "Bissau", "GW"],
  ["Americas", "South America", "Guyana", "Georgetown", "GY"],
  ["Americas", "West Indies", "Haiti", "Port-au-Prince", "HT"],
  [
    "Europe",
    "Southern Europe",
    "Holy See (Vatican City)",
    "Vatican City",
    "VA"
  ],
  ["Americas", "Central America", "Honduras", "Tegucigalpa", "HN"],
  ["Europe", "Central Europe", "Hungary", "Budapest", "HU"],
  ["Europe", "Northern Europe", "Iceland", "Reykjavik", "IS"],
  ["Asia", "South Asia", "India", "New Delhi", "IN"],
  ["Asia", "South East Asia", "Indonesia", "Jakarta", "ID"],
  ["Asia", "South West Asia", "Iran", "Tehran", "IR"],
  ["Asia", "South West Asia", "Iraq", "Baghdad", "IQ"],
  ["Europe", "Western Europe", "Ireland", "Dublin", "IE"],
  ["Asia", "South West Asia", "Israel", "Jerusalem", "IL"],
  ["Europe", "Southern Europe", "Italy", "Rome", "IT"],
  ["Americas", "West Indies", "Jamaica", "Kingston", "JM"],
  ["Asia", "East Asia", "Japan", "Tokyo", "JP"],
  ["Asia", "South West Asia", "Jordan", "Amman", "JO"],
  ["Asia", "Central Asia", "Kazakhstan", "Astana (Akmola)", "KZ"],
  ["Africa", "Eastern Africa", "Kenya", "Nairobi", "KE"],
  ["Oceania", "Pacific", "Kiribati", "Tarawa", "KI"],
  ["Asia", "East Asia", "Korea, North", "P'yongyang", "KP"],
  ["Asia", "East Asia", "Korea, South", "Seoul", "KR"],
  ["Asia", "South West Asia", "Kuwait", "Kuwait", "KW"],
  ["Asia", "Central Asia", "Kyrgyzstan", "Bishkek", "KG"],
  ["Asia", "South East Asia", "Laos", "Vientiane", "LA"],
  ["Europe", "Eastern Europe", "Latvia", "Riga", "LV"],
  ["Asia", "South West Asia", "Lebanon", "Beirut", "LB"],
  ["Africa", "Southern Africa", "Lesotho", "Maseru", "LS"],
  ["Africa", "Western Africa", "Liberia", "Monrovia", "LR"],
  ["Africa", "Northern Africa", "Libya", "Tripoli", "LY"],
  ["Europe", "Central Europe", "Liechtenstein", "Vaduz", "LI"],
  ["Europe", "Eastern Europe", "Lithuania", "Vilnius", "LT"],
  ["Europe", "Western Europe", "Luxembourg", "Luxembourg", "LU"],
  ["Europe", "South East Europe", "Macedonia", "Skopje", "MK"],
  ["Africa", "Indian Ocean", "Madagascar", "Antananarivo", "MG"],
  ["Africa", "Southern Africa", "Malawi", "Lilongwe", "MW"],
  ["Asia", "South East Asia", "Malaysia", "Kuala Lumpur", "MY"],
  ["Asia", "South Asia", "Maldives", "Male (Maale)", "MV"],
  ["Africa", "Western Africa", "Mali", "Bamako", "ML"],
  ["Europe", "Southern Europe", "Malta", "Valletta", "MT"],
  ["Oceania", "Pacific", "Marshall Islands", "Majuro", "MH"],
  ["Americas", "West Indies", "Martinique", "Fort-de-France", "MQ"],
  ["Africa", "Western Africa", "Mauritania", "Nouakchott", "MR"],
  ["Africa", "Indian Ocean", "Mauritius", "Port Louis", "MU"],
  ["Africa", "Indian Ocean", "Mayotte", "Mamoutzou", "YT"],
  ["Americas", "Central America", "Mexico", "Mexico", "MX"],
  ["Oceania", "Pacific", "Micronesia, Federated States of", "Palikir", "FM"],
  ["Europe", "Eastern Europe", "Moldova", "Chisinau", "MD"],
  ["Europe", "Western Europe", "Monaco", "Monaco", "MC"],
  ["Asia", "Northern Asia", "Mongolia", "Ulaanbaatar", "MN"],
  ["Americas", "West Indies", "Montserrat", "Plymouth", "MS"],
  ["Africa", "Northern Africa", "Morocco", "Rabat", "MA"],
  ["Africa", "Southern Africa", "Mozambique", "Maputo", "MZ"],
  ["Asia", "South East Asia", "Myanmar (Burma)", "Rangoon (Yangon)", "MM"],
  ["Africa", "Southern Africa", "Namibia", "Windhoek", "NA"],
  ["Oceania", "Pacific", "Nauru", "no official capital", "NR"],
  ["Asia", "South Asia", "Nepal", "Kathmandu", "NP"],
  ["Europe", "Western Europe", "Netherlands", "Amsterdam", "NL"],
  ["Oceania", "Pacific", "New Caledonia", "Noumea", "NC"],
  ["Oceania", "Pacific", "New Zealand", "Wellington", "NZ"],
  ["Americas", "Central America", "Nicaragua", "Managua", "NI"],
  ["Africa", "Western Africa", "Niger", "Niamey", "NE"],
  ["Africa", "Western Africa", "Nigeria", "Abuja", "NG"],
  ["Oceania", "Pacific", "Niue", "Alofi", "NU"],
  ["Oceania", "Pacific", "Norfolk Island", "Kingston", "NF"],
  ["Oceania", "Pacific", "Northern Mariana Islands", "Saipan", "MP"],
  ["Europe", "Northern Europe", "Norway", "Oslo", "NO"],
  ["Asia", "South West Asia", "Oman", "Muscat", "OM"],
  ["Asia", "South Asia", "Pakistan", "Islamabad", "PK"],
  ["Oceania", "Pacific", "Palau", "Koror", "PW"],
  ["Americas", "Central America", "Panama", "Panama", "PA"],
  ["Oceania", "Pacific", "Papua New Guinea", "Port Moresby", "PG"],
  ["Americas", "South America", "Paraguay", "Asuncion", "PY"],
  ["Americas", "South America", "Peru", "Lima", "PE"],
  ["Asia", "South East Asia", "Philippines", "Manila", "PH"],
  ["Oceania", "Pacific", "Pitcairn Islands", "Adamstown", "PN"],
  ["Europe", "Eastern Europe", "Poland", "Warsaw", "PL"],
  ["Europe", "South West Europe", "Portugal", "Lisbon", "PT"],
  ["Americas", "West Indies", "Puerto Rico", "San Juan", "PR"],
  ["Asia", "South West Asia", "Qatar", "Doha", "QA"],
  ["Africa", "Indian Ocean", "Reunion", "Saint-Denis", "RE"],
  ["Europe", "South East Europe", "Romania", "Bucharest", "RO"],
  ["Asia", "Northern Asia", "Russia", "Moscow", "RU"],
  ["Africa", "Central Africa", "Rwanda", "Kigali", "RW"],
  ["Americas", "West Indies", "Saint Kitts and Nevis", "Basseterre", "KN"],
  ["Americas", "West Indies", "Saint Lucia", "Castries", "LC"],
  [
    "Americas",
    "North America",
    "Saint Pierre and Miquelon",
    "Saint-Pierre",
    "PM"
  ],
  [
    "Americas",
    "West Indies",
    "Saint Vincent and the Grenadines",
    "Kingstown",
    "VC"
  ],
  ["Europe", "Southern Europe", "San Marino", "San Marino", "SM"],
  ["Africa", "Western Africa", "Sao Tome and Principe", "Sao Tome", "ST"],
  ["Asia", "South West Asia", "Saudi Arabia", "Riyadh", "SA"],
  ["Africa", "Western Africa", "Senegal", "Dakar", "SN"],
  ["Africa", "Indian Ocean", "Seychelles", "Victoria", "SC"],
  ["Africa", "Western Africa", "Sierra Leone", "Freetown", "SL"],
  ["Asia", "South East Asia", "Singapore", "Singapore", "SG"],
  ["Europe", "Central Europe", "Slovakia", "Bratislava", "SK"],
  ["Europe", "South East Europe", "Slovenia", "Ljubljana", "SI"],
  ["Oceania", "Pacific", "Solomon Islands", "Honiara", "SB"],
  ["Africa", "Eastern Africa", "Somalia", "Mogadishu", "SO"],
  ["Africa", "Southern Africa", "South Africa", "Pretoria ¹", "ZA"],
  ["Europe", "South West Europe", "Spain", "Madrid", "ES"],
  ["Asia", "South Asia", "Sri Lanka", "Colombo", "LK"],
  ["Africa", "Northern Africa", "Sudan", "Khartoum", "SD"],
  ["Americas", "South America", "Suriname", "Paramaribo", "SR"],
  ["Europe", "Northern Europe", "Svalbard", "Longyearbyen", "SJ"],
  ["Africa", "Southern Africa", "Swaziland", "Mbabane ²", "SZ"],
  ["Europe", "Northern Europe", "Sweden", "Stockholm", "SE"],
  ["Europe", "Central Europe", "Switzerland", "Bern", "CH"],
  ["Asia", "South West Asia", "Syria", "Damascus", "SY"],
  ["Asia", "East Asia", "Taiwan", "Taipei", "TW"],
  ["Asia", "Central Asia", "Tajikistan", "Dushanbe", "TJ"],
  ["Africa", "Eastern Africa", "Tanzania", "Dar es Salaam", "TZ"],
  ["Asia", "South East Asia", "Thailand", "Bangkok", "TH"],
  ["Africa", "Western Africa", "Togo", "Lome", "TG"],
  ["Oceania", "Pacific", "Tokelau", "none", "TK"],
  ["Oceania", "Pacific", "Tonga", "Nuku'alofa", "TO"],
  ["Americas", "West Indies", "Trinidad and Tobago", "Port-of-Spain", "TT"],
  ["Africa", "Northern Africa", "Tunisia", "Tunis", "TN"],
  ["Asia", "South West Asia", "Turkey", "Ankara", "TR"],
  ["Asia", "Central Asia", "Turkmenistan", "Ashgabat", "TM"],
  ["Americas", "West Indies", "Turks and Caicos Islands", "Grand Turk", "TC"],
  ["Oceania", "Pacific", "Tuvalu", "Funafuti", "TV"],
  ["Africa", "Eastern Africa", "Uganda", "Kampala", "UG"],
  ["Europe", "Eastern Europe", "Ukraine", "Kiev", "UA"],
  ["Asia", "South West Asia", "United Arab Emirates", "Abu Dhabi", "AE"],
  ["Europe", "Western Europe", "United Kingdom", "London", "GB"],
  ["Americas", "North America", "United States", "Washington, DC", "US"],
  ["Americas", "South America", "Uruguay", "Montevideo", "UY"],
  ["Asia", "Central Asia", "Uzbekistan", "Tashkent (Toshkent)", "UZ"],
  ["Oceania", "Pacific", "Vanuatu", "Port-Vila", "VU"],
  ["Americas", "South America", "Venezuela", "Caracas", "VE"],
  ["Asia", "South East Asia", "Vietnam", "Hanoi", "VN"],
  ["Americas", "West Indies", "Virgin Islands", "Charlotte Amalie", "VI"],
  ["Oceania", "Pacific", "Wallis and Futuna", "Mata-Utu (on Ile Uvea)", "WF"],
  ["Africa", "Northern Africa", "Western Sahara", "none", "EH"],
  ["Oceania", "Pacific", "Western Samoa", "Apia", "WS"],
  ["Asia", "South West Asia", "Yemen", "Sanaa", "YE"],
  ["Africa", "Southern Africa", "Zambia", "Lusaka", "ZM"],
  ["Africa", "Southern Africa", "Zimbabwe", "Harare", "ZW"]
];
