name: Process TODO comments

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**.yml"

jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Collect TODO
        uses: dtinth/todo-actions@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.TODO_GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.MONGO_URI_TEST }}
